name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Gigalixir
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: mhanberg/gigalixir-action@v0.3.0
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: scoop
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
